### ISSUE TITLE
Error while instantiating git-secrets

### ISSUE THREAD

**Issue by trae-horton** [duo-labs/secret-bridge#2]
I am getting the following error while trying to do the following command:
```
sudo python3 main.py poll
```
```
INFO:GitSecrets:instantiating git-secrets
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/trae/Desktop/secret-bridge/commands/poll/cli.py", line 17, in poll
    poller.poll()
  File "/home/trae/Desktop/secret-bridge/commands/poll/poller.py", line 52, in poll
    Processor.process_event(event)
  File "/home/trae/Desktop/secret-bridge/processor.py", line 55, in process_event
    repo_dir = self._clone_and_establish_baseline(event)
  File "/home/trae/Desktop/secret-bridge/processor.py", line 43, in _clone_and_establish_baseline
    self.findings[repo_url][detector.name] = set(detector.run(repo_dir.name, None, event.repo.html_url))
  File "/home/trae/Desktop/secret-bridge/detectors/gitsecrets.py", line 33, in run
    subprocess.run([self._binary_path, "--register-aws"], cwd=repo_dir, capture_output=True)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by jordan-wright** [comment]
If you build the container yourself, it will copy it into the container. Otherwise, if you’re using the one from Docker Hub, you should be able to mount it as a volume like this:

```
docker run -ti -v $(pwd)/config.toml:config.toml duolabs/secret-bridge poll
```

**Comment by trae-horton** [comment]
gotcha, might want to put that in the README.md for other users. I had to specify the absolute path, see below
```
sudo docker run -ti -v $(pwd)/config.toml:/usr/src/app/config.toml duolabs/secret-bridge poll
```

**Comment by jordan-wright** [comment]
Roger that, will do. Thank you!
