### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mohammed-sec2010** [duo-labs/secret-bridge#22]
$ python3 main.py  poll
INFO:root:Setting up detector: detect-secrets
INFO:root:Setting up detector: git-secrets
INFO:root:Setting up detector: trufflehog
INFO:root:Setting up notifier: slack_webhook
INFO:root:Setting up notifier: console
INFO:root:Monitoring user: Auz
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/secret-bridge/commands/poll/cli.py", line 13, in poll
    Config.create_monitors(client)
  File "/root/secret-bridge/config.py", line 56, in create_monitors
    self.monitors.append(User(user, client))
  File "/root/secret-bridge/models/monitors/user.py", line 16, in __init__
    self.user = client.get_user(self.name)
  File "/usr/local/lib/python3.5/dist-packages/github/MainClass.py", line 231, in get_user
    "/users/" + login
  File "/usr/local/lib/python3.5/dist-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.5/dist-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}

**Comment by ezuri** [comment]
Currently also experiencing this issue when running 'docker run -v C:\Users\USER\secret-bridge\config.toml:/usr/src/app/config.toml -ti --rm -e GITHUB_WATCHER_TOKEN=TOKEN duolabs/secret-bridge poll'

Config:
detectors = [
    "detect-secrets",
    "git-secrets"
]

[auth]
access_token='env'

[monitors]
    organizations = []
    users = ["ezuri"]
    repos = ["secretbridgetest"]

[webhook]
    secret=""
    host="0.0.0.0"

[notifiers.console]
